# Generated by Django 5.2.7 on 2025-12-05 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auto',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='auto',
            name='engineer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autos', to='auto.engineer', verbose_name='Инженер'),
        ),
        migrations.AddField(
            model_name='auto',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='auto.tagpost', verbose_name='Теги'),
        ),
    ]
